# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-21 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sectors',
            fields=[
                ('id_sector', models.AutoField(primary_key=True, serialize=False)),
                ('name_sector', models.CharField(max_length=250)),
                ('description_sector', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='contributeregimen',
            name='id_contribute_regimen',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='countries',
            name='id_contry',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='states',
            name='id_state',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='typeidentification',
            name='id_type_identification',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
