# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-21 15:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utilities', '0002_auto_20181121_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id_brand', models.AutoField(primary_key=True, serialize=False)),
                ('name_brand', models.CharField(max_length=250)),
                ('description_brand', models.TextField()),
                ('logo', models.ImageField(upload_to='logos')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_category', models.AutoField(primary_key=True, serialize=False)),
                ('name_category', models.CharField(max_length=250)),
                ('sector_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilities.Sectors')),
            ],
        ),
        migrations.CreateModel(
            name='ImagesProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images_products')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_product', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('ranking', models.DecimalField(decimal_places=2, max_digits=3)),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Brand')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category')),
            ],
        ),
        migrations.CreateModel(
            name='UnitMeasurement',
            fields=[
                ('id_measure', models.AutoField(primary_key=True, serialize=False)),
                ('name_measure', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='measure_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.UnitMeasurement'),
        ),
        migrations.AddField(
            model_name='product',
            name='provider_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='sector_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilities.Sectors'),
        ),
        migrations.AddField(
            model_name='imagesproduct',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_products', to='products.Product'),
        ),
    ]
